service: AppSyncTest

provider:
  name: aws
  region: ap-northeast-1

plugins:
  - serverless-appsync-plugin

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AppSyncTestTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

custom:
  appSync:
    name: AppSyncTest
    authenticationType: API_KEY   # AppSyncの認証タイプ
    schema: graphql/schema.graphql
    dataSources:
      - type: AMAZON_DYNAMODB
        name: AppSyncTestTable
        config:
          tableName: AppSyncTestTable
          iamRoleStatements:
            - Effect: 'Allow'
              Action:
                - 'dynamodb:Scan'
                - 'dynamodb:Query'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:DeleteItem'
              Resource:
                - 'Fn::Join':
                  - ':'
                  -
                    - 'arn:aws:dynamodb'
                    - Ref: 'AWS::Region'
                    - Ref: 'AWS::AccountId'
                    - 'table/ServerlessAppSyncSampleTable'
